### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [Simplistix/picky-conda#4]
I'm thinking that I could really sue picky-conda for some of my projects.

But I notice that it hasn't seen any updates for a few years.

does that mean:

A) it's stable and works great

or

B) it's not being maintained ?

If A, I'd like to get a conda-forge package going :-)

**Comment by cjw296** [comment]
Based on https://github.com/simplistix/picky-conda/issues/3#issuecomment-992229350 I'm going to recommend https://github.com/conda-incubator/conda-lock.
